### ISSUE TITLE
ImplementsSimpleWFS conformity constraint in the Direct WFS test suite?

### ISSUE THREAD

**Issue by ilkkarinne** [inspire-eu-validation/ets-repository#102]
I don't see a requirement for including the "ImplementsSimpleWFS" conformity constraint in the WFS 2.0 Capabilities. I've checked the OGC WFS 2.0.2 and FES 2.0.2 documents.

The BasicWFS CC in WFS 2.0.2 does require conformance to SimpleWFS CC, but I could not find a requirement or even a recommendation for providing "ImplementsSimpleWFS" constraint. For Basic WFS there is a mandatory constraint "ImplementsBasicWFS"

**Comment by cportele** [comment]
Indeed. http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#139 does not list a ImplementsSimpleWFS constraint, basically because it is superfluous as every WFS must implement this conformance class anyhow - there is nothing to declare. The assertion that tests for this constraint has to be removed.
