### ISSUE TITLE
Dataset vs series

### ISSUE THREAD

**Issue by MichalMed** [inspire-eu-validation/ets-repository#116]
I open this issue to keep track of how it goes. There have been some troubles with definition of dataset and series recently and all we know that it is a problem that has to be solved on the level of MIG. I'm creating this issue to raise its importance.

Case of the Czech Republic -- Series contains all data for the Czech Republic for one schema. Datasets are divided by regions, municipalities or other areas. The files are generated for datasets. It is really important approach towards ATOM, where it really depends on the level in order to be able to filter data based on feed or subfeed information. It is not possible to filter data of subsets, because they are portrayed as entries in ATOM, and only feeds or subfeeds may be returned. This problem needs to find solution on a MIG ground, one way or another, but current situation is ambiguos.

**Comment by michellutz** [comment]
Dear Michal,

thanks for the feedback. As you may know, we are discussing this issue at the upcoming MIG-T meeting, in order to decide whether some additional guidance or best practices need to be developed to come to a more consistent usage of the concept of data set series in INSPIRE.

We are collecting feedback on the approaches in different MS in [this issue in the MIG collaboration platform](https://ies-svn.jrc.ec.europa.eu/issues/3025). I have copied over your input and invite you to follow any follow-up discussion there and/or in the minutes of the [44th MIG-T meeting](https://ies-svn.jrc.ec.europa.eu/projects/mig-inspire/wiki/MIG-T_meeting_44).

Cheers,
Michael

**Comment by MichalMed** [comment]
Thanks Michael, I've been told by JIri Polacek to post it here to have it documented.
