### ISSUE TITLE
Metadata Validation - distributionInfo for ATOM issue

### ISSUE THREAD

**Issue by OscarD31** [inspire-eu-validation/ets-repository#119]
Hello.

In the metadata file for the ATOM service I **had** the following distribution info:

` <gmd:CI_OnlineResource>
                     <gmd:linkage>
                        <gmd:URL>**http://myWeb/atom/ATOM.xml**</gmd:URL>
                     </gmd:linkage>
                  </gmd:CI_OnlineResource>`

With that code, the validation was OK.

But then I discovered that the Tomcat where the ATOM feeds are deployed must serve those feeds as "application/atom+xml" and not as simple XML. 

No big deal according to the "web.xml" file of my Tomcat:

`<mime-mapping>
        <extension>atom</extension>
        <mime-type>application/atom+xml</mime-type>
    </mime-mapping>`

So, if I use the extension .atom instead of .xml, the feed should be served as "application/atom+xml". With that change, my metadata file must be updated:

`<gmd:CI_OnlineResource>
                     <gmd:linkage>
                        <gmd:URL>**http://myWeb/atom/ATOM.atom**</gmd:URL>
                     </gmd:linkage>
                  </gmd:CI_OnlineResource>`

But now, instead of the green validation, I get a yellow one that I do no understand:

> The metadata record has a linkage property, which references a resource with media type 'application/atom+xml' at 'http://myWeb/atom/ATOM.atom' which is not one of the media types indicating an INSPIRE network service. Please review the resource to check that it meets the linkage requirements; specifically, if the resource is a webpage, check that it provides further instructions or a client application that directly accesses the service.

Why is the validator telling me this? It's just the same file, but with different extension.

The TG of the Download Services says that the ATOM feeds (the service one and the dataset ones) must be "application/atom+xml", so I guess the metadata validator should accept "application/atom+xml" as a media type for distribution. It seems that is only accepting the "text/xml" from a GetCapabilities request.

Is this a expected behaviour? Am I missing something?

Thanks for reading!

**Comment by OscarD31** [comment]
Hi.

I forgot to mention that the issue appears in the public deployment of the validator.

Best regards.

**Comment by OscarD31** [comment]
[Metadata_Report.zip](https://github.com/inspire-eu-validation/ets-repository/files/1482226/Metadata_Report.zip)

If it is any help, I have attached the report.

**Comment by cportele** [comment]
@OscarD31 Apologies for not responding earlier to this!

I agree that there should be no error in this case. Right now, however, the test case does not allow an ATOM document, which is probably just an error.

https://github.com/inspire-eu-validation/metadata/blob/1.3/iso-19115-19119/srv-linkage.md

Currently the following are allowed:
* a link to a service capabilities document 
* a link to the service WSDL document [this is not implemented in the ETS as there is no technical guidance that supports this]
* link to a web with further instructions [this is one situation that triggers the manual/yellow result]
* a link to a client application that directly accesses the service [this is one situation that triggers the manual/yellow result]

The last two cases are triggered if the media type is neither 'text/xml', 'application/xml' 'application/vnd.ogc.*'. Since we have the ATOM-based download service, the ATOM media type should be allowed, too. As this is obvious, I will label this as a bug.

At the same time, the ATS (and maybe the TG) should be updated, too. I will therefore also assign this to the MIG-T subgroup.

**Comment by michellutz** [comment]
[2017.4 meeting 2018-03-16] Resolution agreed. ATS & ETS to be updated (Action on JRC Contractors)
