### ISSUE TITLE
Error using DQ_ConformanceResult

### ISSUE THREAD

**Issue by LauraAlemany** [inspire-eu-validation/ets-repository#130]
Hello, 
 
The validator is not analysing correctly data quality reports, except the element DQ_DomainConsistency.
 
If you want to especify the quantitive result  (DQ_QuantitiveResult) there is no problem (See first picture 1_QuantitiveResult ), but if you want to include the ConformanceResult (DQ_ConformanceResult), the validator shows an error saying “the specification is not a child of the gmd:DQ_DomainConsistency” (see second picture 2_ConformanceResult ). This error happens with every  type of data quality element, excluding DQ_DomainConsistency. Therefore, we need you to solve this problem in order to inform of other types of quality elements with a qualitive result and pass the validator.

1_QuantitiveResult: In this picture you can see the data quality element <DQ_ConceptualConsistency> with a quantitive result. There is no error when passing the validator
![1_quantitiveresult](https://user-images.githubusercontent.com/33545308/33875268-086d1c1a-df22-11e7-94ed-5dbacc066d32.jpg)

2_ConformanceResult: In this picture you can see the data quality element <DQ_ConceptualConsistency> with a qualititive result. In this case there is an error when passing the validator. 
![2_conformanceresult](https://user-images.githubusercontent.com/33545308/33875286-13b1b5d6-df22-11e7-8a3a-47489f27fec5.jpg)

Apart from the pictures 1_QuantitiveResult.jpg and 2_ConformanceResult.jpg, I attach the spaignHIDROGRAFIA_IGR.xml just in case you want to pass the validator and see what happens:
[spaignHIDROGRAFIA_IGR.xml.zip](https://github.com/inspire-eu-validation/ets-repository/files/1550814/spaignHIDROGRAFIA_IGR.xml.zip)

More information:
- The link to the Test Report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID1cb0502f-73ca-42e6-a0f0-fb809c2e4285.html 
- The name of the Test that failed (Assertion URI): http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EID1cb0502f-73ca-42e6-a0f0-fb809c2e4285.html?lang=en#EID000348c6-9325-4618-b8f5-cba4dfc65923  

Thank you.

Best Regards,
Laura Alemany

**Comment by cportele** [comment]
Hi @LauraAlemany,

the metadata guidance requires that *any* `gmd:specification` element has `gmd:DQ_DomainConsistency` (see requirement 29) as a parent element, but in your case it is `gmd:DQ_ConceptualConsistency`.

I think this is related to #115. Probably the requirement is too strict and should be relaxed?

**Comment by AntoRot** [comment]
[2017.4 meeting 2018-02-15] The issue was not discussed thoroughly and so no proposal of resolution could be defined. 
The TG requirement 29 (in TG v 1.3), as reported also by @cportele , states that the conformity to any specification (also beyond INSPIRE) has to be reported through an instance of DQ_DomainConsistency (parent element of DQ_ConformanceResult). 
That requirement was further detailed in the TG v. 2.0.1 (see TG Requirements C.20 and C. 21).
No other requirement was defined in TG v 1.3 on using additional ISO data quality elements and measures. However those elements and measures are recommended to be used if the data provider has a own procedure for the quality management (see TG Recommandation 16 kept in the TG v. 2.0.1 as TG Recommendation 1.12). 
In addition, the INSPIRE data specifications contain further recommendations on theme-specific metadata elements for reporting data quality (see section 8.3.2 of DSs); those metadata elements are detailed in the section C.7.11 of the Annex C.7 in TG v. 2.0.1 only referring to quantitative results of the data quality evaluation. The aspects related to the descriptive results, addressed in the section 8.3.2.2 of DSs, are not considered in the mentioned section C.7.11 mainly due to the lack of specific elements for encoding them in the ISO 19115/TS19139 (but properly described with the DQ_DescriptiveResult class in ISO 19157 not in the scope of the TG).
The use of DQ_ConformanceResult as a child element of a parent other than DQ_DomainConsistency is allowed only for providing the descriptive results of the topological consistency (one of metadata elements for interoperability) in the TG v2.0.1. In such a case, TG Requirement 2.8 allows to report the descriptive topological consistency measures using the gmd:report/gmd:DQ_TopologicalConsistency/gmd:result /gmd:DQ_ConformanceResult element citing to the INSPIRE Generic Network Model.
So, for being consistent in a strict way with the requirements in the TG, the proposal of resolution is to keep the current test case but without reporting any error in the case additional data quality elements (other than DQ_DomainConsistency) are used in addition to the instance(s) of DQ_DomainConsistency citing to the INSPIRE implementing rules and to other specifications. Those additional elements could be used to report more precise quality criteria as descriptive results; i.e. the descriptive measures could be reported using the gmd:report/gmd:DQ_xxx/gmd:result /gmd:DQ_ConformanceResult element where DQ_xxx is the ISO element corresponding to one of the data quality elements defined in chapter 7 of DSs (listed in the table in the section C.7 of the Annex C in TG v2.0.1, page 135).

**Comment by LauraAlemany** [comment]
Maybe I don’t explain myself properly with this issue. Therefore, I will try my best with the following explanation:

As you know, Acording to standard ISO metadata, the element "DQ_CoformantResult" could be used for  several quality elements but ATS is very strict because only allowed for DQ_DomainConsistency

Consequently, you can choose from different types of reports (<<gmd:report>>) of Data Quality Info (Inside <<gmd:dataQualityInfo>><<gmd:DQ_DataQuality>>) such as Conceptual Consistency or Domain Consistency.
All of them can have, as a child, the element Conformance Result (<<gmd:result>> <<gmd:DQ_ConformanceResult>>) or Quantitative Result (<<gmd:result>> <<gmd:DQ_QuantitativeResult>>).
The problem is that the validator shows an error when you use the element DQ_ConformanceResult (<<gmd:result>> <<gmd:DQ_ConformanceResult>>) as a child of Conceptual Consistency or another report except from Domain Consistency.

Just to clarify this issue let me give you some examples:

a)	Using these elements there is no error in the validator: 
<<gmd:DQ_DomainConsistency>> <<gmd:DQ_ConceptualConsistency>> <<gmd:result>> <<gmd:DQ_ConformanceResult>>
b)	Using these elements there is the folllowing error message: “the specification is not a child of the gmd:DQ_DomainConsistency” 
<<gmd: DQ_ConformanceResult>> <<gmd:DQ_ConceptualConsistency>> <<gmd:result>> <<gmd:DQ_ConformanceResult>>
c)	Using these elements there is no error in the validator
<<gmd: DQ_ConformanceResult >><<gmd:DQ_ConceptualConsistency>><<gmd:result>><<gmd:DQ_QuantitativeResult>>

There shouldn’t be any error in b)

In “https://github.com/inspire-eu-validation/ets-repository/issues/115”  
@cportele says " The reason is that the test case expects that gmd:DQ_DomainConsistency is a parent element. Maybe the test case needs to be updated to only check INSPIRE-related quality reports, but that would require to specify how to distinguish the two kinds"

Maybe ATS could distinguish the two kinds by testing only that the element DQ_DomainConsistency has DQ_ConformanceResult as a child. And the rest of the cases just leave them, don't analyze it.

This way, metadata can inform diferent quality aspects apart from INSPIRE related quality reports <<gmd:DQ_DomainConsistency>><<gmd:DQ_ConceptualConsistency>><<gmd:result>><<gmd:DQ_ConformanceResult>>. One metadata with Conceptual Consistency (DQ_ConceptualConsistency) could include quality results (DQ_ConformanceResult), not only INSPIRE ones.

**Comment by AntoRot** [comment]
The issue was clear for me and it seems to me that we agree on the resolution.
In brief, the resolution could be as follows:
- ATS checks if there is at least a gmd:report/gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult element citing to the INSPIRE implementing rules and to other specifications (also beyond INSPIRE);
- If there is none, a warning is thrown.
- If instead there is at least one, no error is reported even in the case there are additional data quality elements such as gmd:report/gmd:DQ_ConceptualConsistency/gmd:result/gmd:DQ_ConformanceResult in your case.

**Comment by michellutz** [comment]
[2017.4 meeting 2018-03-16] Antonio's proposal is accepted and shall be implemented in ATS and ETS.
