### ISSUE TITLE
Question regarding XML schemas for metadata

### ISSUE THREAD

**Issue by heidivanparys** [inspire-eu-validation/ets-repository#136]
According to the test for metadata:

> Official XML schemas are currently found in two separate locations:
> * ISO repository for publicly available standards. The ISO 19139 schemas can be found at http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/.
> * OGC Schema repository. The ISO 19139 schemas are located at http://schemas.opengis.net/iso/19139/20070417/ and http://schemas.opengis.net/iso/19139/20060504/. The difference in the schemas is the GML version. The version dated "2007-04-17" uses GML 3.2.1, the version dated "2006-06-04" use GML 3.2.0, which was never approved or published by OGC. The major difference is that GML 3.2.0 schemas are defined in the namespace http://www.opengis.net/gml whereas GML 3.2.1 schemas are defined in the namespace http://www.opengis.net/gml/3.2.
>     The ISO AP schemas are located at http://schemas.opengis.net/csw/2.0.2/profiles/apiso/. The ISO AP schemas are bound to the ISO 19139 schemas dated "2006-06-04".
>     The schemas located in the ISO repository for publicly available standards are the same as the ISO 19139 schemas dated "2007-04-17".

Metadata schemas are also available on http://www.isotc211.org/2005/

I was wondering, what is the status and history of these? Are they valid or not? A very quick look gives fx a difference in gco/basicTypes.xsd on line 393, where xlink:simpleLink is used instead of xlink:simpleAttrs

**Comment by cportele** [comment]
http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/ and http://schemas.opengis.net/iso/19139/20070417/ should basically be the same schema documents, but in different locations.

http://www.isotc211.org/2005/ is also the same schema documents, but obviously it has not been updated with the W3C Xlink schema that has been published by W3C some years ago (instead of the stop gap schema that we have used in OGC until then). This is outdated. Do not use these schema documents.

http://schemas.opengis.net/iso/19139/20060504/ is a mistake due to the use of an unofficial, unpublished intermediate draft version of GML. But it is normative in the CSW 2.0.2 standard, so it is published in the official OGC schema repository. There was an attempt in the past to correct this with a corrigendum, but that was rejected. These schema documents should only be used with CSW 2.0.2.

http://schemas.opengis.net/csw/2.0.2/profiles/apiso/ is a schema defined by the OGC CSW ISO-AP standard.

**Comment by heidivanparys** [comment]
Ok, thanks for the explanation.
